


simulation_params:
  num_years: 35
  names_of_parents: ["benjy", "inbar"]
  balance_in_bank_account: 0

initial:
  location: "israel"
  num_kids: 0



  incomes:
    # incomes
    benjy:
      # jobs
      jobs:
        main_job:
          base_salary_after_taxes: 18.5
          probability_of_loosing_job: 0.2
          percentage_of_base_salary_for_stocks: 0.0
          bonus_fraction_of_annual_income: 0.0
          dollar_amount_per_year: 0
          has_pension_plan: True
          has_keren_hishtalmut_plan: True

      # portfolios
      porfolios:
        main_portfolio:
          amount_invested: 100
          minimal_amount_for_withdrawl: 50

        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0


    inbar:
      # jobs
      jobs:
        main_job:
          base_salary_after_taxes: 16.7
          probability_of_loosing_job: 0.2
          percentage_of_base_salary_for_stocks: 0.1
          bonus_fraction_of_annual_income: 0.1
          dollar_amount_per_year: 30
          has_pension_plan: True
          has_keren_hishtalmut_plan: True

      # portfolios
      porfolios:
        main_portfolio:
          amount_invested: 40
          minimal_amount_for_withdrawl: 50

        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0


initial_expenses:
  - 

