expenses_timeline: null
initial:
  expenses: null
  incomes:
    benjy:
      jobs:
        main_job:
          base_salary_after_taxes: 10.5
          bonus_fraction_of_annual_income: 0.0
          has_keren_hishtalmut_plan: true
          has_pension_plan: true
          options_per_year: 0
          percentage_of_base_salary_for_stocks: 0.0
          probability_of_loosing_job: 0.2
      porfolios:
        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
    job14:
      jobs:
        main_job:
          base_salary_after_taxes: 18.5
          bonus_fraction_of_annual_income: 0.0
          has_keren_hishtalmut_plan: !!python/tuple
          - &id001 !!python/tuple
            - 'False'
          - 1
          has_pension_plan: !!python/tuple
          - *id001
          - 1
          options_per_year: 0
          percentage_of_base_salary_for_stocks: 0.0
          probability_of_loosing_job: 5.0
      porfolios:
        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
    job15:
      jobs:
        main_job:
          base_salary_after_taxes: 18.5
          bonus_fraction_of_annual_income: 0.0
          has_keren_hishtalmut_plan: !!python/tuple
          - &id002 !!python/tuple
            - 'False'
          - 1
          has_pension_plan: !!python/tuple
          - *id002
          - 1
          options_per_year: 0
          percentage_of_base_salary_for_stocks: 0.0
          probability_of_loosing_job: 0.2
      porfolios:
        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
    job23:
      jobs:
        main_job:
          base_salary_after_taxes: 18.5
          bonus_fraction_of_annual_income: 0.0
          has_keren_hishtalmut_plan: !!python/tuple
          - &id003 !!python/tuple
            - 'False'
          - 1
          has_pension_plan: !!python/tuple
          - *id003
          - 1
          options_per_year: 0
          percentage_of_base_salary_for_stocks: 0.0
          probability_of_loosing_job: 0.2
      porfolios:
        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
    job3:
      jobs:
        main_job:
          base_salary_after_taxes: 18.5
          bonus_fraction_of_annual_income: 0.0
          has_keren_hishtalmut_plan: !!python/tuple
          - &id004 !!python/tuple
            - 'False'
          - 1
          has_pension_plan: !!python/tuple
          - *id004
          - 1
          options_per_year: 10.0
          percentage_of_base_salary_for_stocks: 0.0
          probability_of_loosing_job: 3.0
      porfolios:
        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0
  location: israel
  num_kids: 0
simulation_params:
  balance_in_bank_account: 0
  names_of_parents:
  - benjy
  - job3
  - job23
  - job14
  - job15
  num_years: 35
  number_of_repetitions: 3
