


simulation_params:
  num_years: 35
  # names_of_parents: ["benjy", "inbar"]
  names_of_parents: ["benjy"]
  balance_in_bank_account: 0
  number_of_repetitions: 3

initial:
  location: "israel"
  num_kids: 0
  incomes:
    benjy:
      # jobs
      jobs:
        main_job:
          base_salary_after_taxes: 10.5
          probability_of_loosing_job: 0.2
          percentage_of_base_salary_for_stocks: 0.0
          bonus_fraction_of_annual_income: 0.0
          options_per_year: 0
          has_pension_plan: True
          has_keren_hishtalmut_plan: True

      # portfolios
      porfolios:
        main_portfolio:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        keren_hishtalmut:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        pension:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        company_stock:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

        options:
          amount_invested: 0
          minimal_amount_for_withdrawl: 0

 

  expenses:
 

expenses_timeline:
  # first_kid: 
  #   year: 2
  #   method: have_kid
  #   params: 
  #     location: israel

  # second_kid: 
  #   year: 5
  #   method: have_kid
  #   params: 
  #     location: israel

  # third_kid: 
  #   year: 8
  #   method: have_kid
  #   params: 
  #     location: israel

  # buy_house:
  #   year: 5
  #   method: add_expense
  #   params:
  #     expense_name: "house"
  #     expense_type: "House"
  #     expense_params:
  #       full_price: 3000
  #       down_payment: 600
  #       monthly_payment: 8

  # move_out_of_apartment:
  #   year: 5
  #   method: remove_expense
  #   params:
  #     expense_name: "apartment"

  # stop_having_big_family_trips:
  #   year: 20
  #   method: remove_expense
  #   params:
  #     expense_name: "big_family_trip1"
